language: go

go:
  - 1.5.2
  - 1.4
  - 1.3
  - tip

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - psql -c 'create database distributor;' -U postgres
  - psql -c 'create database distributor_test;' -U postgres
  - goose up

script:
  - ./script/test

before_install:
  - sudo apt-get update
  - sudo apt-get install -y tor

install:
  - ./script/bootstrap
  - ./script/recycle
