language: go

go:
  - 1.5.2
  - 1.4
  - 1.3
  - tip

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - psql -c 'create database distributor;' -U postgres
  - psql -c 'create database distributor_test;' -U postgres
  - goose up

script:
  - ./script/test

install:
  - go get -u github.com/gpmgo/gopm
  - go get -u gopkg.in/godo.v1/cmd/godo
  - go get
  - godo the-thing
  - gopm get
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - go build
